# Generated by Django 3.0.5 on 2020-05-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='cost',
            new_name='costs',
        ),
        migrations.RemoveField(
            model_name='test',
            name='disease',
        ),
        migrations.AddField(
            model_name='test',
            name='disease',
            field=models.ManyToManyField(to='backend.Disease'),
        ),
    ]
